services:
  - type: web
    name: chatboost-landing
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /dashboard
        destination: /dashboard.html
      - type: rewrite
        source: /*
        destination: /index.html
